package org.scheez.schema.dao;

import javax.sql.DataSource;

import org.scheez.schema.def.ColumnType;
import org.scheez.schema.model.ObjectName;
import org.scheez.schema.model.Sequence;
import org.scheez.util.DbC;

public class SchemaDaoHsqldb extends SchemaDaoAnsi
{
    public SchemaDaoHsqldb(DataSource dataSource)
    {
        super(dataSource);
    }
    
    @Override
    public ColumnType getExpectedColumnType(ColumnType columnType)
    {
        if (columnType == ColumnType.FLOAT)
        {
            columnType = ColumnType.DOUBLE;
        }
        return columnType;
    }

    @Override
    protected String getSchemaName(ObjectName objectName)
    {
       return objectName.toUpperCase().getSchemaName();
    }

    @Override
    protected String getObjectName(ObjectName objectName)
    {
        return objectName.toUpperCase().getObjectName();
    }

    @Override
    protected String getColumnName(String columnName)
    {
        return columnName.toUpperCase();
    }

    @Override
    protected String getAutoIncrement()
    {
        return " GENERATED BY DEFAULT AS IDENTITY";
    }
    
    @Override
    public void createSequence(Sequence sequence)
    {

    }

    public static class Factory extends SchemaDaoFactory
    {

        @Override
        public boolean isSupported(String databaseProduct, String databaseVersion)
        {
            DbC.throwIfNullArg(databaseProduct);
            return databaseProduct.trim().startsWith("HSQL");
        }

        @Override
        public SchemaDao create (DataSource dataSource)
        {
            DbC.throwIfNullArg(dataSource);
            return new SchemaDaoHsqldb (dataSource);
        }

    }

}
